from Imports import *

emptyColumn = []

def createEmptyColumn():
    global emptyColumn

    emptyColumn = [
            "DATE", 
            "TIME", 
            "MODEL CODE", 
            "PROCESS S/N", 
            "S/N", 
            "PASS/NG", 
            "VOLTAGE MAX (V)", 
            "WATTAGE MAX (W)", 
            "CLOSED PRESSURE_MAX (kPa)", 
            "VOLTAGE Middle (V)", 
            "WATTAGE Middle (W)", 
            "AMPERAGE Middle (A)", 
            "CLOSED PRESSURE Middle (kPa)", 
            "VOLTAGE MIN (V)", 
            "WATTAGE MIN (W)", 
            "CLOSED PRESSURE MIN (kPa)",

            "Process 1 Model Code",
            "Process 1 S/N",
            "Process 1 ID",
            "Process 1 NAME",
            "Process 1 Regular/Contractual",
            "Process 1 Em2p",
            "Process 1 Em2p Lot No",
            "Process 1 Em2p Inspection 3 Average Data",
            "Process 1 Em2p Inspection 4 Average Data",
            "Process 1 Em2p Inspection 5 Average Data",
            "Process 1 Em2p Inspection 10 Average Data",
            "Process 1 Em2p Inspection 3 Minimum Data",
            "Process 1 Em2p Inspection 4 Minimum Data",
            "Process 1 Em2p Inspection 5 Minimum Data",
            "Process 1 Em2p Inspection 3 Maximum Data",
            "Process 1 Em2p Inspection 4 Maximum Data",
            "Process 1 Em2p Inspection 5 Maximum Data",
            "Process 1 Em3p",
            "Process 1 Em3p Lot No",
            "Process 1 Em3p Inspection 3 Average Data",
            "Process 1 Em3p Inspection 4 Average Data",
            "Process 1 Em3p Inspection 5 Average Data",
            "Process 1 Em3p Inspection 10 Average Data",
            "Process 1 Em3p Inspection 3 Minimum Data",
            "Process 1 Em3p Inspection 4 Minimum Data",
            "Process 1 Em3p Inspection 5 Minimum Data",
            "Process 1 Em3p Inspection 3 Maximum Data",
            "Process 1 Em3p Inspection 4 Maximum Data",
            "Process 1 Em3p Inspection 5 Maximum Data",
            "Process 1 Harness",
            "Process 1 Harness Lot No",
            "Process 1 Frame",
            "Process 1 Frame Lot No",
            "Process 1 Frame Inspection 1 Average Data", 
            "Process 1 Frame Inspection 2 Average Data", 
            "Process 1 Frame Inspection 3 Average Data", 
            "Process 1 Frame Inspection 4 Average Data", 
            "Process 1 Frame Inspection 5 Average Data", 
            "Process 1 Frame Inspection 6 Average Data", 
            "Process 1 Frame Inspection 7 Average Data", 
            "Process 1 Frame Inspection 1 Minimum Data", 
            "Process 1 Frame Inspection 2 Minimum Data", 
            "Process 1 Frame Inspection 3 Minimum Data", 
            "Process 1 Frame Inspection 4 Minimum Data", 
            "Process 1 Frame Inspection 5 Minimum Data", 
            "Process 1 Frame Inspection 6 Minimum Data", 
            "Process 1 Frame Inspection 7 Minimum Data", 
            "Process 1 Frame Inspection 1 Maximum Data", 
            "Process 1 Frame Inspection 2 Maximum Data", 
            "Process 1 Frame Inspection 3 Maximum Data", 
            "Process 1 Frame Inspection 4 Maximum Data", 
            "Process 1 Frame Inspection 5 Maximum Data", 
            "Process 1 Frame Inspection 6 Maximum Data", 
            "Process 1 Frame Inspection 7 Maximum Data", 
            "Process 1 Bushing",
            "Process 1 Bushing Lot No",
            "Process 1 ST",
            "Process 1 Actual Time",
            "Process 1 NG Cause",
            "Process 1 Repaired Action",

            "Process 2 Model Code",
            "Process 2 S/N",
            "Process 2 ID",
            "Process 2 NAME",
            "Process 2 Regular/Contractual",
            "Process 2 M4x40 Screw",
            "Process 2 M4x40 Screw Lot No",
            "Process 2 Rod Blk",
            "Process 2 Rod Blk Lot No",
            "Process 2 Rod Blk Tesla 1 Average Data",
            "Process 2 Rod Blk Tesla 2 Average Data",
            "Process 2 Rod Blk Tesla 3 Average Data",
            "Process 2 Rod Blk Tesla 4 Average Data",
            "Process 2 Rod Blk Tesla 1 Minimum Data",
            "Process 2 Rod Blk Tesla 2 Minimum Data",
            "Process 2 Rod Blk Tesla 3 Minimum Data",
            "Process 2 Rod Blk Tesla 4 Minimum Data",
            "Process 2 Rod Blk Tesla 1 Maximum Data",
            "Process 2 Rod Blk Tesla 2 Maximum Data",
            "Process 2 Rod Blk Tesla 3 Maximum Data",
            "Process 2 Rod Blk Tesla 4 Maximum Data",
            "Process 2 Rod Blk Inspection 1 Average Data",
            "Process 2 Rod Blk Inspection 2 Average Data",
            "Process 2 Rod Blk Inspection 3 Average Data",
            "Process 2 Rod Blk Inspection 4 Average Data",
            "Process 2 Rod Blk Inspection 5 Average Data",
            "Process 2 Rod Blk Inspection 6 Average Data",
            "Process 2 Rod Blk Inspection 7 Average Data",
            "Process 2 Rod Blk Inspection 8 Average Data",
            "Process 2 Rod Blk Inspection 9 Average Data",
            "Process 2 Rod Blk Inspection 1 Minimum Data",
            "Process 2 Rod Blk Inspection 2 Minimum Data",
            "Process 2 Rod Blk Inspection 3 Minimum Data",
            "Process 2 Rod Blk Inspection 4 Minimum Data",
            "Process 2 Rod Blk Inspection 5 Minimum Data",
            "Process 2 Rod Blk Inspection 6 Minimum Data",
            "Process 2 Rod Blk Inspection 7 Minimum Data",
            "Process 2 Rod Blk Inspection 8 Minimum Data",
            "Process 2 Rod Blk Inspection 9 Minimum Data",
            "Process 2 Rod Blk Inspection 1 Maximum Data",
            "Process 2 Rod Blk Inspection 2 Maximum Data",
            "Process 2 Rod Blk Inspection 3 Maximum Data",
            "Process 2 Rod Blk Inspection 4 Maximum Data",
            "Process 2 Rod Blk Inspection 5 Maximum Data",
            "Process 2 Rod Blk Inspection 6 Maximum Data",
            "Process 2 Rod Blk Inspection 7 Maximum Data",
            "Process 2 Rod Blk Inspection 8 Maximum Data",
            "Process 2 Rod Blk Inspection 9 Maximum Data",
            "Process 2 Df Blk",
            "Process 2 Df Blk Lot No",
            "Process 2 Df Blk Inspection 1 Average Data",
            "Process 2 Df Blk Inspection 2 Average Data",
            "Process 2 Df Blk Inspection 3 Average Data",
            "Process 2 Df Blk Inspection 4 Average Data",
            "Process 2 Df Blk Inspection 1 Minimum Data",
            "Process 2 Df Blk Inspection 2 Minimum Data",
            "Process 2 Df Blk Inspection 3 Minimum Data",
            "Process 2 Df Blk Inspection 4 Minimum Data",
            "Process 2 Df Blk Inspection 1 Maximum Data",
            "Process 2 Df Blk Inspection 2 Maximum Data",
            "Process 2 Df Blk Inspection 3 Maximum Data",
            "Process 2 Df Blk Inspection 4 Maximum Data",
            "Process 2 Df Blk Tensile Rate Of Change Average",
            "Process 2 Df Blk Tensile Rate Of Change Minimum",
            "Process 2 Df Blk Tensile Rate Of Change Maximum",
            "Process 2 Df Blk Tensile Start Force Average",
            "Process 2 Df Blk Tensile Start Force Minimum",
            "Process 2 Df Blk Tensile Start Force Maximum",
            "Process 2 Df Blk Tensile Terminating Force Average",
            "Process 2 Df Blk Tensile Terminating Force Minimum",
            "Process 2 Df Blk Tensile Terminating Force Maximum",
            "Process 2 Df Ring",
            "Process 2 Df Ring Lot No",
            "Process 2 Washer",
            "Process 2 Washer Lot No",
            "Process 2 Lock Nut",
            "Process 2 Lock Nut Lot No",
            "Process 2 ST",
            "Process 2 Actual Time",
            "Process 2 NG Cause",
            "Process 2 Repaired Action",

            "Process 3 Model Code",
            "Process 3 S/N",
            "Process 3 ID",
            "Process 3 NAME",
            "Process 3 Regular/Contractual",
            "Process 3 Frame Gasket",
            "Process 3 Frame Gasket Lot No",
            "Process 3 Casing Block",
            "Process 3 Casing Block Lot No",
            "Process 3 Casing Block Inspection 1 Average Data",
            "Process 3 Casing Block Inspection 1 Minimum Data",
            "Process 3 Casing Block Inspection 1 Maximum Data",
            "Process 3 Casing Gasket",
            "Process 3 Casing Gasket Lot No",
            "Process 3 M4x16 Screw 1",
            "Process 3 M4x16 Screw 1 Lot No",
            "Process 3 M4x16 Screw 2",
            "Process 3 M4x16 Screw 2 Lot No",
            "Process 3 Ball Cushion",
            "Process 3 Ball Cushion Lot No",
            "Process 3 Frame Cover",
            "Process 3 Frame Cover Lot No",
            "Process 3 Partition Board",
            "Process 3 Partition Board Lot No",
            "Process 3 Built In Tube 1",
            "Process 3 Built In Tube 1 Lot No",
            "Process 3 Built In Tube 2",
            "Process 3 Built In Tube 2 Lot No",
            "Process 3 Head Cover",
            "Process 3 Head Cover Lot No",
            "Process 3 Casing Packing",
            "Process 3 Casing Packing Lot No",
            "Process 3 M4x12 Screw",
            "Process 3 M4x12 Screw Lot No",
            "Process 3 Csb L",
            "Process 3 Csb L Lot No",
            "Process 3 Csb R",
            "Process 3 Csb R Lot No",
            "Process 3 Head Packing",
            "Process 3 Head Packing Lot No",
            "Process 3 ST",
            "Process 3 Actual Time",
            "Process 3 NG Cause",
            "Process 3 Repaired Action",

            "Process 4 Model Code",
            "Process 4 S/N",
            "Process 4 ID",
            "Process 4 NAME",
            "Process 4 Regular/Contractual",
            "Process 4 Tank",
            "Process 4 Tank Lot No",
            "Process 4 Upper Housing",
            "Process 4 Upper Housing Lot No",
            "Process 4 Cord Hook",
            "Process 4 Cord Hook Lot No",
            "Process 4 M4x16 Screw",
            "Process 4 M4x16 Screw Lot No",
            "Process 4 Tank Gasket",
            "Process 4 Tank Gasket Lot No",
            "Process 4 Tank Cover",
            "Process 4 Tank Cover Lot No",
            "Process 4 Housing Gasket",
            "Process 4 Housing Gasket Lot No",
            "Process 4 M4x40 Screw",
            "Process 4 M4x40 Screw Lot No",
            "Process 4 PartitionGasket",
            "Process 4 PartitionGasket Lot No",
            "Process 4 M4x12 Screw",
            "Process 4 M4x12 Screw Lot No",
            "Process 4 Muffler",
            "Process 4 Muffler Lot No",
            "Process 4 Muffler Gasket",
            "Process 4 Muffler Gasket Lot No",
            "Process 4 VCR",
            "Process 4 VCR Lot No",
            "Process 4 ST",
            "Process 4 Actual Time",
            "Process 4 NG Cause",
            "Process 4 Repaired Action",
            
            "Process 5 Model Code",
            "Process 5 S/N",
            "Process 5 ID",
            "Process 5 NAME",
            "Process 5 Regular/Contractual",
            "Process 5 Rating Label",
            "Process 5 Rating Label Lot No",
            "Process 5 ST",
            "Process 5 Actual Time",
            "Process 5 NG Cause",
            "Process 5 Repaired Action",
            
            "Process 6 Model Code",
            "Process 6 S/N",
            "Process 6 ID",
            "Process 6 NAME",
            "Process 6 Regular/Contractual",
            "Process 6 Vinyl",
            "Process 6 Vinyl Lot No",
            "Process 6 ST",
            "Process 6 Actual Time",
            "Process 6 NG Cause",
            "Process 6 Repaired Action",

            "Process 1 SERIAL NO",
            "Process 2 SERIAL NO",
            "Process 3 SERIAL NO",
            "Process 4 SERIAL NO",
            "Process 5 SERIAL NO",
            "Process 6 SERIAL NO"
        ]